- name: Setup configs
  hosts: roman
  connection: local

  tasks:
    - name: Get SSM parameters
      set_fact:
        env: "{{ lookup('aws_ssm', 'environment') }}"

    - name: Get environment variables
      set_fact:
        account_id: "{{ lookup('env', 'ACCOUNT_ID') }}"
        ecr_account_id: "{{ lookup('env', 'ECR_ACCOUNT_ID') }}"

    - name: Show gathered variables
      debug:
        msg:
          - "env - {{ env }}"
          - "account_id - {{ account_id }}"
          - "ecr_account_id - {{ ecr_account_id }}"
    - name: Create jupyterhub-deploy setup-env
      template:
        src: templates/setup-env.j2
        dest: /home/ec2-user/jupyterhub-deploy/test-setup-env


