- name: Configure JupyterHub
  hosts: all
  connection: local

  tasks:
    - name: Generate setup-env
      include_tasks: generate-config.yml
      vars:
        config_path: "{{ jh_dir }}/setup-env"
        template_path: "templates/jupyterhub/setup-env.j2"
