- name: Setup terraform configs
  hosts: localhost
  connection: local

  tasks:
    - name: Get SSM parameters
      set_fact:
        env: "{{ lookup('aws_ssm', 'environment') }}"

    - name: Get environment variables
      set_fact:
        account_id: "{{ lookup('env', 'ACCOUNT_ID') }}"
        ecr_account_id: "{{ lookup('env', 'ECR_ACCOUNT_ID') }}"

    - name: Show gathered variables
      debug: msg="ENV = {{ env }}, ACCOUNT_ID = {{ account_id }}, ECR_ACCOUNT_ID = {{ ecr_account_id }}"

